### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by npavlovikj** [biobakery/melonnpan#1]
Hi @himelmallick ,

I am a contributor to "bioconda", https://bioconda.github.io/, that packages bioinformatics tools for easier installation and distribution. I would like to create a conda package for "melonnpan". However, one of the requirements for this, is to have a tagged release. Therefore, can you please tag a release and create a tarball for it so I can proceed?

Thank you in advance, and please let me know if you have any questions regarding this request.

--
Natasha

**Comment by himelmallick** [comment]
Hi @npavlovikj - thanks for checking in - this is currently in my TODO list. I will let you know once it is done. 

Many thanks,
Himel
