### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by leechfish** [biobakery/melonnpan#11]
Hi there,

I am trying to run predict_metabolites.R on a food project and I am wondering if it is possible without training the data first, for a food microbiome? I am getting the following error: 

Error in melonnpan::melonnpan.predict(metag = metag, weight.matrix = weight.matrix,  :
  No common IDs found between training and test data. Execution halted!

I am also wondering if my input is the problem. After extracting the Uniref90 lines from the merge_metaphlan_tables.py output, I transposed the table so that it looks like the test data set. The initial error was a segfault so I subsetted the table to the first 1000 columns to test it on a smaller dataset. That is when I got the error above. Im not sure at this point if the problem is how I created the melonnpan input, or if it is a problem with a non-human environment. Any help would be greatly appreciated, including the commands to go from genefamilies tsv outputs from humann, to the txt input for melonnpan.

**Comment by himelmallick** [comment]
Hi @leechfish - my sincere apologies for getting to this so late as I was away from the project for a while but fortunately it was always on my radar. About this specific issue, your data curation seems correct based on your description and it is likely the latter as not much overlap is expected between the UniRef90s of MelonnPan's human training data and your non-human feature set.
