### ISSUE TITLE
MelonnPan with Arbitrary Predictors

### ISSUE THREAD

**Issue by krchhabria** [biobakery/melonnpan#13]
Hello, 
I am trying to input picrust-derived data from humann2 to MelonnPan – I understand the limitations of this, but we are trying to validate further analysis using these predictive models. The biobakery tutorial mentions that "Customizing MelonnPan-Train for arbitrary predictors (i.e. different from the default UniRef90)" is upcoming, but I was wondering if the resources to do so are already available, given the fact that the picrust output has limited resolution. Thank you!

**Comment by himelmallick** [comment]
Hi @krchhabria - thanks for trying out MelonnPan. I am afraid this is still a work in progress and I do not have a definitive answer when it will become available. Please check back later for updated information.
