### ISSUE TITLE
Error in is.data.frame(x) : object 'train.weight' not found when running predict_metabolites.R

### ISSUE THREAD

**Issue by DrKADunn** [biobakery/melonnpan#14]
Just installed melonnpan and associated R libraries (although I will note that dyplr is needed and not in the list)

When running predict_metabolites.R on the supplied data file melonnpan.test.data.txt I get the following error:

Error in is.data.frame(x) : object 'train.weight' not found
Calls: <Anonymous> ... intersect -> unique -> as.vector -> colnames -> is.data.frame
Execution halted

It creates the MelonnPan_RTSI.txt but nothing more.

Here is the command ran and screen output:

Rscript predict_metabolites.R -i data/melonnpan.test.data.txt -o Output/   

Loading required package: glmnet
Loading required package: Matrix
Loaded glmnet 3.0-2

Loading required package: foreach
Loading required package: getopt
Loading required package: doParallel
Loading required package: iterators
Loading required package: parallel
Loading required package: vegan
Loading required package: permute
Loading required package: lattice
This is vegan 2.5-6
Loading required package: data.table
Loading required package: ggplot2
Loading required package: AssocTests
Loading required package: cluster
Loading required package: mvtnorm
Loading required package: combinat

Attaching package: 'combinat'

The following object is masked from 'package:utils':

    combn

Loading required package: fExtremes
Loading required package: timeDate
Loading required package: timeSeries
Loading required package: fBasics
Loading required package: fGarch
Loading required package: optparse
Loading required package: tibble
Loading required package: GenABEL
Loading required package: MASS
Loading required package: GenABEL.data
Running MelonnPan-Predict using the following parameters: 
$options
$options$metag
[1] "data/melonnpan.test.data.txt"

$options$criticalpoint
[1] 0.9793

$options$corr.method
[1] "pearson"

$options$output
[1] "Output/"

$options$help
[1] FALSE

$args
character(0)

Error in is.data.frame(x) : object 'train.weight' not found
Calls: <Anonymous> ... intersect -> unique -> as.vector -> colnames -> is.data.frame
Execution halted

**Comment by himelmallick** [comment]
Hi @DrKADunn - I think you are not using the most updated version of the code in which this issue is fixed. Let me know if you run into any issue (feel free to send me an email for faster reply) when you run it after reinstalling the package. Thanks!
