### ISSUE TITLE
A little bug in melonnpan_predict.R

### ISSUE THREAD

**Issue by zhifeng-essen** [biobakery/melonnpan#15]
I came across the same problem as #14 . I checked the code in `melonnpan_predict.R` and noticed a strange: 

```
 # Load weight matrix
  if (is.null(weight.matrix)){
    weight.matrix<-melonnpan::melonnpan.trained.model
  } else{ 
    train.weight<-as.data.frame(t(readTable(weight.matrix)))
  }
```

The variable `train.weight` will not actually be set if weight.matrix is not provided.

**Comment by himelmallick** [comment]
Hi @zhifeng-essen - I think you are not using the most updated version of the code in which this issue is fixed. Let me know if you run into any issue (feel free to send me an email for faster reply) when you run it after reinstalling the package. Thanks!
