### ISSUE TITLE
problems with melonpann.train

### ISSUE THREAD

**Issue by samkjm12** [biobakery/melonnpan#16]
This is the code I used to run the script according to your tutorial and also using your datasets from GitHub

Rscript train_metabolites.R —i data/melonnpan.training.compounds.txt -g data/melonnpan.training.data.txt -o Output/

I got the following error message : 
Error in apply(metab, 2, ArcSin) : dim(X) must have a positive length
Calls: <Anonymous> -> apply
In addition: Warning message:
In rep(seq(nfolds), length.out = nrow(metab)) :
  first element used of 'length.out' argument
Execution halted

There could be some problem with apply? Because it is taking in the first column of the dataset or something? Thank you for your time.

**Comment by himelmallick** [comment]
@samkjm12 - it looks like there is an extra minus sign on your code which is causing the error. Could you please try running the following `Rscript train_metabolites.R -i data/melonnpan.training.compounds.txt -g data/melonnpan.training.data.txt -o Output/`? Many thanks!
