### ISSUE TITLE
melonnpan for 16s data + Installation failed 

### ISSUE THREAD

**Issue by ramay** [biobakery/melonnpan#17]
Hi,
I am trying to install melonnpan and it fails with this error:
`Error: Failed to install 'melonnpan' from GitHub:
  (converted from warning) packages ‘GenABEL’, ‘GenABEL.data’ are not available (for R version 3.6.2)`

I am using R version 3.6.2. Should I use a previous R version in conda envirnoment

AIso, I  want to use melonnpan for 16s data. The tutorial is about metagenomics functional profiles by HUMAnN2 so how can I run with taxonomic profiles from databases like RDP or Silva.
Thanks!
Hena

**Comment by himelmallick** [comment]
Hi @ramay, you need to install the old versions of these two packages separately as mentioned in the **How to Install** section (https://github.com/biobakery/melonnpan) before installing MelonnPan. It currently does not support 16S, however, even though it could be supported in a future version. Please check back soon for updates.

**Comment by ramay** [comment]
Thanks Himel,
I was interested in melonnpan for amplicon sequencing only at this point. From reading the paper, it seemed that it was implemented as amplicon data was used. I will keep an eye on your github page for updates.

Hena

**Comment by himelmallick** [comment]
Hi Hena - yes you are right that we did apply it to amplicon data but we did not include the trained amplicon models in the package without validating them in independent test data (which we did not have access to).
