### ISSUE TITLE
Metabolite number in the default model in the package

### ISSUE THREAD

**Issue by EllieYin567** [biobakery/melonnpan#18]
Hi, Dr. Mallick - The default model in the melonnpan package only contains 80 metabolites, but according to your paper (https://www.nature.com/articles/s41467-019-10927-1), there seem to be a model with 466 metabolites with identities confirmed to lab standard? Is there any specific reason that the default model in the package only contains 80? Also in the paper, supplementary figure 8, what would be the difference between "all compounds" and "unique compounds"? Thank you very much!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - we only included those metabolites in the package that were confirmed against laboratory standards with unique cluster IDs. In other words, for the rest of the compounds, we did not have confidently assigned labels. As you are possibly aware, in untargeted MS-based metabolomics, multiple compounds can belong to a cluster, and we conducted separate confirmatory analyses based on both unique compounds and all compounds (i.e. unique + non-unique).

**Comment by himelmallick** [comment]
Hi @EllieYin567 - we only included those metabolites in the package that were confirmed against laboratory standards. In other words, for the rest of the compounds, we did not have confidently assigned labels. As you might be aware, in untargeted MS-based metabolomics, non-unique ID mapping occurs during the compound identification stage. Therefore, we conducted separate confirmatory analyses based on both unique compound IDs (i.e. compounds with one-to-one mapping with HMDB) and all compounds (i.e compounds with both one-to-one and many-to-one mappings with HMDB). I hope it makes sense!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - we only included those metabolites in the package that were confirmed against laboratory standards **with unique HMBD identifiers**. As non-unique ID mapping occurs during the compound identification stage, we conducted separate confirmatory analyses based on both unique compound IDs (i.e. compounds with one-to-one mapping with HMDB, **n = 80**) and all compounds (i.e compounds with both one-to-one and many-to-one mappings with HMDB, **n = 466**). I hope it makes sense!

**Comment by EllieYin567** [comment]
Thank you for explaining! For "many-to-one", do you mean there are multiple HMDB mapped results for one MS signal or multiple MS signals mapped to one HMDB ID? Is there any specific reason that you decide to only include one-to-one relationship compound? It seems to me that this greatly reduced the number of metabolites the model could predict (from 466 to 80)...

**Comment by himelmallick** [comment]
Hi @EllieYin567 - it's multiple MS signals mapped to one HMDB ID - we had to make a choice between quality and quantity in order to avoid situations like 'multiple copies of metabolite X in the final output'. I am sure there will be some workarounds in the future versions but we could not think of a less confusing way to report these compounds.
