### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by JoannaDrx** [biobakery/melonnpan#2]
Error : package or namespace load failed for ‘melonnpan’ in loadNamespace(package, lib.loc):
 cyclic namespace dependency detected when loading ‘melonnpan’, already loading ‘melonnpan’
Error : unable to load R code in package ‘melonnpan’
ERROR: lazy loading failed for package ‘melonnpan’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/melonnpan’
Installation failed: Command failed (1)

**Comment by himelmallick** [comment]
Hey @JoannaDrx - I just pushed an update - could you please let me know if that resolves the installation issue on your end?

**Comment by JoannaDrx** [comment]
Yes, it works now! Thank you for the quick update.
