### ISSUE TITLE
"y is constant; gaussian glmnet fails at standardization step"

### ISSUE THREAD

**Issue by Jalapenobadger** [biobakery/melonnpan#20]
Hey, sorry me again.
We actually already had appropriate metabolite data from previous work I didn't know about, and I'm now getting the title error. 

> k-fold CV: 10Error in { : task 5 failed - "y is constant; gaussian glmnet fails at standardization step"

I've seen your previous response on this error:

> this will happen if, during the cross-validation, any of the response variables (i.e. metabolites) only contains a few non-unique values within a fold. Could you please make sure the metabolites have at least 5 or 10 unique values post-filtering as glmnet and melonnpan.train does 10-fold CV by default? Alternatively, you could also do a 3-fold or 5-fold CV if further filtering is not feasible. Hope this helps. Thanks!

So looking through the tutorial, it mentions that you pass metabolite data through basic filtering, what tool did you use to do this, and what is it filtering out specifically?

When you say that they must have at least 5-10 unique values, does that mean that using 4 sequence samples is not enough, because for a given metabolite to be useable it must have abundance values on at least 5 different sequences? Would dropping to 4-fold be appropriate? Thanks!

-Pete

**Comment by himelmallick** [comment]
Hi Pete - you could do simple filtering based on prevalence and abundance as follows (assuming that metabolites (in columns) and samples (in rows) are stored in `metab_table`):

```r

# TSS normalization for the purpose of filtering
library(vegan)
metab_table_rel_abd <- decostand(metab_table, method="total", MARGIN=1, na.rm=TRUE)
 
# Prevalence and abundance filtering
abd_threshold = 1e-04
prev_threshold = 0.1
metab_table_rel_abd_filtered <- metab_table_rel_abd[, colSums(metab_table_rel_abd > abd_threshold) > nrow(metab_table_rel_abd)* prev_threshold] 
```

You can also do variance filtering as follows: 

```r
# Filter out features with little variance 
sds <- apply(metab_table, 2, sd)
metab_table_filtered<- metab_table[, which(sds > quantile(sds, prob = 0.5))]
```

Note that, these thresholds are arbitrary and there is no one-size-fits-all filtering solution for every dataset. The goal is to remove metabolites with little variance so that we can concentrate on high-quality data for final modeling.

**Comment by himelmallick** [comment]
To answer your other question, could you please let me know what is your sample size?

**Comment by Jalapenobadger** [comment]
My sample size is 4, in the sense of sequence data from 36hr, 40hr, 44hr,
and 48hr runs, but if the quality will be drastically lower without it I
could maybe grab 8 more samples all the way down to 4hr, for which I know
there is already metabolite data. I'm just working with 4 samples to test
things out for my PI.

Also I will try out each of those filtering suggestions, and see if that
helps.

Thanks again, you've been exceptionally helpful and responsive.
-Pete

**Comment by himelmallick** [comment]
I am afraid with such a small sample size there is hardly any chance of getting reliable predictions. I will suggest applying n-fold CV (LOOCV) in stead of the default but I highly doubt that will get you anything.

**Comment by himelmallick** [comment]
Also since you have paired metabolite and sequencing data, you might want to check out another tool MIMOSA: https://github.com/borenstein-lab/MIMOSA. Either way, let me know how it goes.

**Comment by Jalapenobadger** [comment]
Alright, I will try to get the remainder of the data and try it out again.

**Comment by Jalapenobadger** [comment]
Alright, coming back to this, I have run the data through the filtering you suggested in quite a few combinations, and while I no longer get the error above, running the training completes but results in no output, with a variable number of errors in the log depending on the number of columns of metabolites, all related to this:

> In cor(as.numeric(as.vector(pred[, i])), as.numeric(as.vector(metab[,  ... :
>   the standard deviation is zero

Simply running a check in excel on each column of data none of the stdev's come out to be zero, and I have tried filtering out columns from around 300+ metabolites all the way down to just 27, which leads me to believe it is not due to a lack of rigorous enough filtering, but rather some sort of format issue.

I can send show some of the data if that would help to diagnose the problem.

Thanks,
-Pete
