### ISSUE TITLE
In cor(as.numeric(as.vector(pred[, i])), as.numeric(as.vector(metab[,  ... 

### ISSUE THREAD

**Issue by Jalapenobadger** [biobakery/melonnpan#21]
Alright, coming back to this, I have run the data through the filtering you suggested in quite a few combinations, and while I no longer get the error above, running the training completes but results in no output, with a variable number of errors in the log depending on the number of columns of metabolites, all related to this:

> In cor(as.numeric(as.vector(pred[, i])), as.numeric(as.vector(metab[,  ... :
>   the standard deviation is zero

Simply running a check in excel on each column of data none of the stdev's come out to be zero, and I have tried filtering out columns from around 300+ metabolites all the way down to just 27, which leads me to believe it is not due to a lack of rigorous enough filtering, but rather some sort of format issue.

I can send show some of the data if that would help to diagnose the problem.

Thanks,
-Pete

_Originally posted by @Jalapenobadger in https://github.com/biobakery/melonnpan/issues/20#issuecomment-645467225_

**Comment by himelmallick** [comment]
Hi Pete - since the overall cross-validation and model building process ran without error, I believe there is not enough predictive power in your metagenomics features and your MelonnPan predictions are not better than random (which translates to an intercept-only model with a constant predicted value).

**Comment by Jalapenobadger** [comment]
So in this case the standard deviation = zero refers not to the input but
the output lines? There is no significant difference between expected
outputs for any inputs? If that is the case, I can probably dial back the
filtering and find a sweet spot, I was assuming that it was standard
deviation referring to the input values.
-Pete

**Comment by himelmallick** [comment]
Hi Pete - sure thing. The errors you are seeing occur during the calculation of correlations between measured and predicted metabolites, which can only happen after MelonnPan has successfully run the prediction algorithm.

**Comment by Jalapenobadger** [comment]
Ah, thanks for the clarification!
-Pete
