### ISSUE TITLE
NOTE: Instead of opening issues in github, please consider creating a new topic in https://forum.biobakery.org/. Please read for more details. 

### ISSUE THREAD

**Issue by sagun98** [biobakery/melonnpan#22]
[The bioBakery support forum](https://forum.biobakery.org/) provides software support and tutorials for methods for microbial community profiling developed by the Huttenhower lab. Please consider creating a new topic in[ the bioBakery support forum](https://forum.biobakery.org/) before opening issues in Github.

**Comment by sejyoti** [comment]
After using the OTU table in HUMAnN2, we get four types of output files regarding UNIfrac90 abundance values along with pathways. After using such file outputs as training model data mentioned in the github melonpann site, we did not get the suitable output. We have used the conda command line for getting the outputs but it did not work as an input file for melonpann and the output of HUMAnN2 does not match equally. I would request you to give a clearer version of the input and output for this melonpann metabolite prediction.
