### ISSUE TITLE
melonnpan.train cannot reproduce

### ISSUE THREAD

**Issue by EllieYin567** [biobakery/melonnpan#5]
Hello again~ I am using the melonpan.train to train my dataset; however, I found out each time I ran the command, the results are a little different, although I set my seed the same every time. Do you have any suggestions? Many thanks!

Below is the code I used in R. 
melonnpan.train(metab = metab_final, metag = kegg_final, seed = 1234, outputDirectory = paste0(path,"/melonnpan_predt/kegg_train/"))

**Comment by himelmallick** [comment]
Hi @EllieYin567 - sorry for the delay in getting back to you. This is a well-known issue with the cv.glmnet function on which MelonnPan relies on (see here: https://stats.stackexchange.com/questions/97777/variablity-in-cv-glmnet-results). Since the folds are selected at random in cv.glmnet, the results are expected to be a little different each time (due to randomness). At this point, I do not have plans to modify the cv.glmnet function but you can reduce this randomness by running MelonnPan many times, and averaging the predictions. Hope this helps!

**Comment by EllieYin567** [comment]
Hi, @himelmallick Thank you for getting back to me and providing your input on this matter! So, I would assume in this case, for "melonnpan.train" function, whether set.seed or not does not matter because cv.glmnet will randomly choose folds?

**Comment by himelmallick** [comment]
Hi @EllieYin567 - I just added a quick fix in the "melonnpan.train" function by defining the foldid outside the cv.glmnet call. I have not tested it yet but feel free to give it a shot. Let me know if you still see variability in the results. Thanks for trying it out!

**Comment by EllieYin567** [comment]
@himelmallick Thank you for fixing the function and I am trying to install the new melonnpan package from R. However, it threw out an error message as below. I suspect it could be related to the changes in the melonnpan.train function. Could you help to check? Many thanks!!

Error in parse(outFile) : 
  /private/var/folders/tb/rvr52vps5x14ktnfdd7994fw0000gr/T/RtmpOEoaLV/R.INSTALL515d33c33632/melonnpan/R/melonnpan_train.R:60:3: unexpected symbol
59:   # sequence features' Transformation (DEFAULT Rank-Based Inverse Normal)
60:   metag
      ^
ERROR: unable to collate and parse R files for package ‘melonnpan’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/melonnpan’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/melonnpan’
Error: Failed to install 'melonnpan' from GitHub:
  (converted from warning) installation of package ‘/var/folders/tb/rvr52vps5x14ktnfdd7994fw0000gr/T//RtmpufKXDT/file512262175af3/melonnpan_0.99.0.tar.gz’ had non-zero exit status

**Comment by EllieYin567** [comment]
Hello @himelmallick , 
1. for the error message I posted earlier, "melonnpan_train.R:60:3: unexpected symbol", I noticed in melonnpan.train function, there is a missing ")" in "foldid <- sample(rep(seq(nfolds) , length.out = nrow(metab))". Adding this ")" seems to fix this error. 
2. However, it seems that "CV.ENET" does not take "foldid" argument, as I got the following error later on: 
Error in CV.ENET(metab = metab, metag = metag, alpha = alpha, lambda.choice = lambda.choice,  : unused argument (foldid = foldid)

Do you have any suggestions in how to fix the problem? many thanks!!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - I just fixed the issues above which I missed earlier as I forgot to re-build the package (which would have thrown an error). If it still does not work, I will have a chance to check it later this week when I will update the tutorial. Thanks either way!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - I just updated the tutorial page which should give you more information on the usage of MelonnPan-Train. Please let me know if you encounter any other issues.
