### ISSUE TITLE
customize weight matrix not working for melonnpan.predict

### ISSUE THREAD

**Issue by EllieYin567** [biobakery/melonnpan#6]
Hi, Dr. Mallick @himelmallick  - Thank you for fixing the previous issue on melonnpan.train reproducibility and I was able to run this step successfully. 
Now I have a question on melonnpan.predict using my customized weight matrix. 
The weight matrix is the output from melonnpan.train. 
I imported the matrix using the command:
kegg_weight_matrix <- read.table(file="MelonnPan_Weight_Matrix.txt", header = T, row.names = 1, sep="\t")
And I ran melonnpan.predict using 
melonnpan.predict(metag=kegg_final, weight.matrix = kegg_weight_matrix, train.metag = kegg_final, output = "kegg_predict/").

The error message I got is:
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 4

When I looked into the function and found out this step in the function caused the error - "intercept <- as.numeric(levels(intercept))[intercept]". It seems I did not format my weight matrix correctly as there is no level information in my weight matrix. 
So, my question is what would be the correct format for customized weight matrix? 
Many thanks in advance.

**Comment by himelmallick** [comment]
Hi @EllieYin567 - thanks for providing important feedback on various functionalities of MelonnPan as we try to optimize the package. You are right that you should not have level information in your customized weight matrix. It should work as long as the input is a numeric matrix (assuming the dimensions are correct). I removed the portion of the code which was hard-coded previously to match the default weight matrix saved as a data frame (which is no longer the case). This fix should work for both your customized weight matrix as well as the default, let me know if it doesn't or if you encounter any other issue. Many thanks!

**Comment by EllieYin567** [comment]
@himelmallick melonnpan.predict is working fine now. Thank you for your help and I am happy to contribute to this awesome software!
