### ISSUE TITLE
error for melonnpan.train

### ISSUE THREAD

**Issue by EllieYin567** [biobakery/melonnpan#7]
Hi, Dr. Mallick @himelmallick - 
I ran into the following error when running melonnpan.train and hope could get some insight here. 
The command I used is:
melonnpan.train(metab = metab_final_kegg, metag = kegg_final, seed = 1234, outputDirectory = paste0(path,"/melonnpan_predt/kegg_train/"))
The error message is:
Error in melonnpan.summarize(metab = metab, pred = pred, method = method,  : 
  All measurements should be normalized to proportions.

I double checked my input metab by "any(metab_final_kegg<0 | metab_final_kegg>1)" and the output is "FALSE". However, I noticed in the melonnpan.train function, metab is transformed first by "metab <- apply(metab, 2, ArcSin)" before CV.NET, but was not transformed back during "melonnpan.summarize" in the later part of the function. Could this be the reason that causes the problem? Or is there anything I am missing here? This function (melonnpan.train) does work for my other dataset though. 

Thanks much!!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - there is an explicit back-transformation step right after CV.ENET so I don't have a clue what might be going on - could you share a minimum reproducible example so that I can debug? Many thanks!

**Comment by EllieYin567** [comment]
@himelmallick Thank you for the quick feedback! 
Here I attached the example data (kegg_final_SUB1.csv - the gene data; metab_final_kegg_SUB1.csv - the metabolome data).[Archive.zip](https://github.com/biobakery/melonnpan/files/3503500/Archive.zip)

Commands:
library(melonnpan)
metab <- read.csv("metab_final_kegg_SUB1.csv", header = T, row.names = 1,stringsAsFactors = FALSE)
metag <- read.csv("kegg_final_SUB1.csv", header = T, row.names = 1,stringsAsFactors = FALSE)
melonnpan.train(metab = metab, metag = metag, seed = 1234, outputDirectory = "~/Desktop/test/")

Error message:
Error in melonnpan.summarize(metab = metab, pred = pred, method = method,  : 
  All measurements should be normalized to proportions.

Please let me know whether you could replicate the error. Many thanks!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - I was able to reproduce the error. Thanks for sharing the example files. Apparently, there can be values greater than 1 after the arc-sine square root transformation, which I missed earlier (it never happened in my own datasets) and you are right that it does not make sense to place a sanity check after transformation and prediction. I just removed that chunk from the `melonnpan.summarize` script. Give it a try! It should work now! Thanks again for catching the bug!

**Comment by himelmallick** [comment]
@EllieYin567 - Also a word of caution - it is not uncommon to observe a high correlation when the model size is 1, which is not something we should rely on. I noticed a couple in the output files generated by your example which you should absolutely discard as spurious. I am adding it in my TODO list to remove such cases by default.

**Comment by morgvevans** [comment]
Hi,
I appear to be having a similar issue. I am using what R says is melonnpan v. 0.99.0.

Any help would be great! Thank you!

The main message I am getting is 'Error in if (any(test.metag < 0) || any(test.metag > 1)) stop("All measurements should be normalized to proportions.") : 
  missing value where TRUE/FALSE needed'

I double checked this file & all columns sum to 1. I've also attached my input file in a zip (as you can see I am transposing in R so this has samples in columns, not rows).

[humann2_genefamilies_04242020_manualrelab.tsv.zip](https://github.com/biobakery/melonnpan/files/4530187/humann2_genefamilies_04242020_manualrelab.tsv.zip)

**Here is my R input Code**

metag_df <- read.table("humann2_genefamilies_04242020_manualrelab.tsv.txt", header = TRUE, stringsAsFactors = FALSE)
head(metag_df)


metag_transpose <- as.data.frame(t(as.matrix(metag_df)))

library(data.table)
head(metag_transpose)

rownames(metag_transpose) <- colnames(metag_df)
colnames(metag_transpose) <- rownames(metag_df)
metag_transpose ## this is the final chart

write.table(metag_transpose, "metag.txt", append = FALSE, sep = "\t",
            row.names = TRUE, col.names = TRUE)

library(melonnpan)
melonnpan.predict(metag_transpose)

**Here is the output I get**
> library(melonnpan)
Loading required package: glmnet
Loading required package: Matrix
Loaded glmnet 3.0-2

Loading required package: foreach
Loading required package: getopt
Loading required package: doParallel
Loading required package: iterators
Loading required package: parallel
Loading required package: vegan
Loading required package: permute
Loading required package: lattice
This is vegan 2.5-6
Loading required package: ggplot2
Learn more about the underlying theory at https://ggplot2-book.org/
Loading required package: AssocTests
Loading required package: cluster
Loading required package: mvtnorm
Loading required package: combinat

Attaching package: ‘combinat’

The following object is masked from ‘package:utils’:

    combn

Loading required package: fExtremes
Loading required package: timeDate
Loading required package: timeSeries
Loading required package: fBasics
Loading required package: fGarch
Loading required package: optparse
Loading required package: tibble
Loading required package: GenABEL
Loading required package: MASS
Loading required package: GenABEL.data
**> melonnpan.predict(metag_transpose)
Error in if (any(test.metag < 0) || any(test.metag > 1)) stop("All measurements should be normalized to proportions.") : 
  missing value where TRUE/FALSE needed**
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In Ops.factor(left, right) : ‘<’ not meaningful for factors
2: In Ops.factor(left, right) : ‘<’ not meaningful for factors
3: In Ops.factor(left, right) : ‘<’ not meaningful for factors
4: In Ops.factor(left, right) : ‘<’ not meaningful for factors
5: In Ops.factor(left, right) : ‘<’ not meaningful for factors
6: In Ops.factor(left, right) : ‘<’ not meaningful for factors
7: In Ops.factor(left, right) : ‘<’ not meaningful for factors
8: In Ops.factor(left, right) : ‘<’ not meaningful for factors
9: In Ops.factor(left, right) : ‘<’ not meaningful for factors
10: In Ops.factor(left, right) : ‘<’ not meaningful for factors
11: In Ops.factor(left, right) : ‘<’ not meaningful for factors
12: In Ops.factor(left, right) : ‘<’ not meaningful for factors
13: In Ops.factor(left, right) : ‘<’ not meaningful for factors
14: In Ops.factor(left, right) : ‘<’ not meaningful for factors
15: In Ops.factor(left, right) : ‘<’ not meaningful for factors
16: In Ops.factor(left, right) : ‘<’ not meaningful for factors
17: In Ops.factor(left, right) : ‘<’ not meaningful for factors
18: In Ops.factor(left, right) : ‘<’ not meaningful for factors
19: In Ops.factor(left, right) : ‘<’ not meaningful for factors
20: In Ops.factor(left, right) : ‘<’ not meaningful for factors
21: In Ops.factor(left, right) : ‘<’ not meaningful for factors
22: In Ops.factor(left, right) : ‘<’ not meaningful for factors
23: In Ops.factor(left, right) : ‘<’ not meaningful for factors
24: In Ops.factor(left, right) : ‘<’ not meaningful for factors
25: In Ops.factor(left, right) : ‘<’ not meaningful for factors
26: In Ops.factor(left, right) : ‘<’ not meaningful for factors
27: In Ops.factor(left, right) : ‘<’ not meaningful for factors
28: In Ops.factor(left, right) : ‘<’ not meaningful for factors
29: In Ops.factor(left, right) : ‘<’ not meaningful for factors
30: In Ops.factor(left, right) : ‘<’ not meaningful for factors
31: In Ops.factor(left, right) : ‘<’ not meaningful for factors
32: In Ops.factor(left, right) : ‘<’ not meaningful for factors
33: In Ops.factor(left, right) : ‘<’ not meaningful for factors
34: In Ops.factor(left, right) : ‘<’ not meaningful for factors
35: In Ops.factor(left, right) : ‘<’ not meaningful for factors
36: In Ops.factor(left, right) : ‘<’ not meaningful for factors
37: In Ops.factor(left, right) : ‘<’ not meaningful for factors
38: In Ops.factor(left, right) : ‘<’ not meaningful for factors
39: In Ops.factor(left, right) : ‘<’ not meaningful for factors
40: In Ops.factor(left, right) : ‘<’ not meaningful for factors
41: In Ops.factor(left, right) : ‘<’ not meaningful for factors
42: In Ops.factor(left, right) : ‘<’ not meaningful for factors
43: In Ops.factor(left, right) : ‘<’ not meaningful for factors
44: In Ops.factor(left, right) : ‘<’ not meaningful for factors
45: In Ops.factor(left, right) : ‘<’ not meaningful for factors
46: In Ops.factor(left, right) : ‘<’ not meaningful for factors
47: In Ops.factor(left, right) : ‘<’ not meaningful for factors
48: In Ops.factor(left, right) : ‘<’ not meaningful for factors
49: In Ops.factor(left, right) : ‘<’ not meaningful for factors
50: In Ops.factor(left, right) : ‘<’ not meaningful for factors

**Comment by himelmallick** [comment]
Hi @morgvevans - thanks for sharing the data and code. I checked whether there are values greater than 1 using `any(metag_transpose>1)` which returned TRUE. Also, I will suggest using unstratified features only (to save computation time) as the stratified features remain unused in the Melonnpan algorithm. Let me know if you come across any other issues.

**Comment by morgvevans** [comment]
Hi @himelmallick , thanks for the help. I went back and got the unstratified features table.

I have gone back & done this several different ways, but no matter what I do, the "relabund" columns per sample that comes out of humann2_renorm_table don't fully sum to 1 exactly - it's like 1.00007 or 0.99992, etc, which I assume is the reason for the error.
I've tried doing it manually in excel and I am having the same issue. 
I'm probably missing something important or an easy workaround - do you have any suggestions? Thanks

**Comment by himelmallick** [comment]
@morgvevans - I would suggest renormalizing the `humann2_renorm_table` output using TSS normalization if that makes sense. Let me know if that resolves the issue.
