### ISSUE TITLE
melonnpan.train result interpretation

### ISSUE THREAD

**Issue by EllieYin567** [biobakery/melonnpan#9]
Hi @himelmallick - I have been using melonnpan train on my customized datasets. One observation is that for certain projects, the well-predicted metabolites all have model.size =1. I am wondering how should I interpret this results? These are probably noise and should be removed? Does this also mean MelonnPan, is not suitable for prediction for this particular dataset? Many thanks as always!

**Comment by himelmallick** [comment]
Hi @EllieYin567 - as you rightly guessed, for those cases, MelonnPan could not reliably find predictive features and they should be removed in general - this is not surprising as we would expect some metabolites to be not predictable by the metagenomic features - as you can see, in this thread: https://github.com/biobakery/melonnpan/issues/8, I am planning to remove these metabolites by default in the next update. Until then, you can still use those metabolites for which the model size is a decent number (i.e. >1). Many thanks!
